name: Build Eleventy


on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [20.x]

    steps:
        - uses: actions/checkout@v2


        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - name: install dependencies & build
        - run: npm ci
        - run: npm start


        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            publish_dir: ./build

            github_token: ${{ secrets.GITHUB_TOKEN }}


